
os:
  - linux
dist: trusty

language: c

install:
  - export CHOOSENIM_CHOOSE_VERSION="0.19.4"
  - |
      curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
      sh init.sh -y
  - export PATH=$HOME/.nimble/bin:$PATH

script:
  - make test
